# Generated by Django 4.2.4 on 2023-08-11 15:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="avatar",
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="currency",
            field=models.CharField(
                choices=[("krw", "Korean Won"), ("usd", "Dollar")], max_length=5
            ),
        ),
    ]
