# Generated by Django 4.2.4 on 2023-08-11 15:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("rooms", "0003_room_name_alter_amenity_description"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="amenity",
            options={"verbose_name_plural": "Amenities"},
        ),
    ]
