# Generated by Django 4.1.1 on 2022-11-21 03:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("houses", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="house",
            old_name="price",
            new_name="price_per_night",
        ),
    ]
